# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_mailTemplates', '0005_auto_20160201_1358'),
        ('django_documents', '0001_initial'),
        ('django_podio', '0008_auto_20160331_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDocumentHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach_document_to_item', models.BooleanField(default=False, verbose_name='Determina si el documento generado va a ser adjuntado al item de PODIO o no')),
                ('from_email', models.CharField(max_length=256, verbose_name='El correo desde el cual se env\xeda el documento y el correo, o un valor num\xe9rico del field_id donde se puede encontrar')),
                ('to_email', models.CharField(max_length=256, verbose_name='El correo electr\xf3nico del destinatario, o un valor num\xe9rico con el field_id donde se puede encontrar')),
                ('cc_email', models.CharField(max_length=256, verbose_name='El correo electr\xf3nico de un cc, o un valor num\xe9rico con el field_id donde se puede encontrar')),
                ('document', models.ForeignKey(help_text='El documento que se generar\xe1 autom\xe1ticamente cada vez que se llama este hook. Es importante que los valores de los campos a llenar dentro de dicho documento hayan sido debidamente llenados con los field_id correspondientes de la aplicaci\xf3n de PODIO', on_delete=django.db.models.deletion.CASCADE, to='django_documents.ODTTemplate')),
                ('emailTemplate', models.ForeignKey(help_text='EL template del email que se le va a enviar a la persona.', on_delete=django.db.models.deletion.CASCADE, to='django_mailTemplates.Email')),
                ('hook', models.ForeignKey(help_text='El hook de la aplicaci\xf3n y del item al cual est\xe1 asociado este hook completo. EL m\xf3dulo de dicho hook debe ser hook_email_document.py', on_delete=django.db.models.deletion.CASCADE, to='django_podio.Hook')),
            ],
        ),
    ]
