# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex_hooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaildocumenthook',
            old_name='emailTemplate',
            new_name='email_template',
        ),
        migrations.AddField(
            model_name='emaildocumenthook',
            name='description',
            field=models.TextField(default='asd', verbose_name='Descripci\xf3n: Qu\xe9 hace este hook exactamente?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emaildocumenthook',
            name='name',
            field=models.CharField(default='asd', max_length=64, verbose_name='Nombre del hook. Es bueno que sea descriptivo sin ser muy largo'),
            preserve_default=False,
        ),
    ]
