# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex_hooks', '0003_auto_20160422_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.PositiveIntegerField(verbose_name='La field_id del campo sobre el cual se quiere configurar la condici\xf3n')),
                ('value', models.CharField(max_length=32, verbose_name='El valor que debe tomar el campo seleccionado anteriormente para que este hook se dispare')),
                ('condition_type', models.CharField(default='=', max_length=16, verbose_name='El tipo de condici\xf3n. En este momento este valor no importa, pero eventualmente habr\xe1 m\xe1s tipos de condiciones')),
                ('complex_hook', models.ForeignKey(help_text='El hook al cual pertenece esta condici\xf3n', on_delete=django.db.models.deletion.CASCADE, to='complex_hooks.EmailDocumentHook')),
            ],
        ),
    ]
