# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex_hooks', '0005_auto_20160425_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='complex_hook',
            field=models.ForeignKey(help_text='El hook al cual pertenece esta condici\xf3n', on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='complex_hooks.EmailDocumentHook'),
        ),
    ]
