# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex_hooks', '0006_auto_20160425_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveIntegerField(verbose_name='El valor del field_id que ser\xe1 utilizado para reemplazar el campo en el correo o en el documento generado')),
                ('value', models.CharField(max_length=32, verbose_name='El valor dentro del template del correo o el template del documento que ser\xe1 llenado con el campo del item de PODIO identificado con el field_id ingresado previamente')),
            ],
        ),
        migrations.AlterField(
            model_name='emaildocumenthook',
            name='attach_document_to_item',
            field=models.BooleanField(default=True, verbose_name='Determina si el documento generado va a ser adjuntado al item de PODIO o no'),
        ),
        migrations.AlterField(
            model_name='emaildocumenthook',
            name='cc_email',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='El correo electr\xf3nico de un cc, o un valor num\xe9rico con el field_id donde se puede encontrar'),
        ),
        migrations.AlterField(
            model_name='emaildocumenthook',
            name='to_email',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='El correo electr\xf3nico del destinatario, o un valor num\xe9rico con el field_id donde se puede encontrar'),
        ),
        migrations.AddField(
            model_name='transformer',
            name='complex_hook',
            field=models.ForeignKey(help_text='El hook al cual pertenece este transformador', on_delete=django.db.models.deletion.CASCADE, related_name='transformers', to='complex_hooks.EmailDocumentHook'),
        ),
    ]
