# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex_hooks', '0007_auto_20160425_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformer',
            name='key',
            field=models.CharField(max_length=32, verbose_name='El valor del field_id que ser\xe1 utilizado para reemplazar el campo en el correo o en el documento generado'),
        ),
    ]
