# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex_hooks', '0009_datemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='datemanager',
            name='variable',
            field=models.CharField(blank=True, help_text='El valor dentro de los PDFs o correos electr\xf3nicos que ser\xe1 reemplazado por esta fecha', max_length=32, null=True, verbose_name='Variable'),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='key',
            field=models.CharField(help_text='El valor del field_id que ser\xe1 utilizado para reemplazar el campo en el correo o en el documento generado', max_length=32, verbose_name='PODIO Field ID'),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='value',
            field=models.CharField(help_text='El valor dentro del template del correo o el template del documento que ser\xe1 llenado con el campo del item de PODIO identificado con el field_id ingresado previamente', max_length=32, verbose_name='Variable'),
        ),
    ]
