# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex_hooks', '0010_auto_20160712_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datemanager',
            name='formatting',
            field=models.CharField(choices=[('ingles', 'ingles'), ('espa\xf1ol', 'espa\xf1ol'), ('dia/mes/a\xf1o', 'dia/mes/a\xf1o'), ('dia', 'dia'), ('mes', 'mes'), ('month', 'month'), ('num_mes', 'num_mes'), ('a\xf1o', 'a\xf1o')], help_text='Los formatos que puede tomar la fecha. Puede estar en ingl\xe9s, en espa\xf1ol, o en formato num\xe9rico', max_length=16, verbose_name='Formatos'),
        ),
    ]
