# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-13 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex_hooks', '0013_auto_20160812_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildocumenthook',
            name='generate_odt',
            field=models.BooleanField(default=False, help_text='Si se marca, el documento va a ser generado como un word en vez de un pdf, lo cual permitir\xe1 modificaciones adicionales', verbose_name='Documento en word?'),
        ),
    ]
