# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex_hooks', '0015_expapodioloader'),
    ]

    operations = [
        migrations.AddField(
            model_name='expapodioloader',
            name='area',
            field=models.CharField(choices=[('ogv', 'ogv'), ('ogip', 'ogip'), ('igv', 'igv'), ('igip', 'igip'), ('ogx', 'ogx'), ('icx', 'icx')], default='igcdp', help_text='El \xe1rea sobre la cual se quiere hacer la consulta.', max_length=8, verbose_name='Area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expapodioloader',
            name='days_past',
            field=models.PositiveSmallIntegerField(default=1, help_text='La cantidad de d\xedas en el pasado desde la que se desea solicitar los datos. Si es uno, se pedir\xe1n los de ayer.', verbose_name='Dias en el pasado'),
        ),
        migrations.AddField(
            model_name='expapodioloader',
            name='interaction',
            field=models.CharField(choices=[('registered', 'registered'), ('contacted', 'contacted'), ('applied', 'applied'), ('accepted', 'accepted'), ('an_signed', 'an_signed'), ('approved', 'approved'), ('realized', 'realized')], default='approved', help_text='El tipo de interacci\xf3n del usuario o de la oportunidad dentro de EXPA', max_length=16, verbose_name='Interacci\xf3n'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expapodioloader',
            name='lc_id',
            field=models.PositiveSmallIntegerField(default=1395, help_text='El EXPA ID del LC espec\xedfico sobre el que se desea hacer la consulta.', verbose_name='LC ID'),
        ),
    ]
