# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-04 16:06
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('complex_hooks', '0017_auto_20160910_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expapodioloader',
            name='area',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ogv', 'ogv'), ('ogt', 'ogt'), ('oge', 'oge'), ('igv', 'igv'), ('igt', 'igt'), ('ige', 'ige')], help_text='El \xe1rea sobre la cual se quiere hacer la consulta.', max_length=8, verbose_name='Area'),
        ),
    ]
